# Generated by Django 4.1.7 on 2023-03-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecNode',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('knowledge', models.PositiveSmallIntegerField()),
                ('maxKnowledge', models.PositiveSmallIntegerField()),
                ('unlocked', models.BooleanField(default=False)),
                ('parent', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
