# Generated by Django 4.1.7 on 2023-03-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specnode',
            name='parent',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
