# Generated by Django 4.1.7 on 2023-03-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0003_alter_specnode_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specnode',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='specnode',
            name='unlocked',
        ),
    ]
